"""add continent name column in weather history.

Revision ID: 0b29004ae30a
Revises: a929c5493ec7
Create Date: 2025-10-30 17:33:33.532122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b29004ae30a'
down_revision: Union[str, Sequence[str], None] = 'a929c5493ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('continentweatherinfo', sa.Column('continent_name', sa.String(), nullable=False))
    op.create_index(op.f('ix_continentweatherinfo_continent_name'), 'continentweatherinfo', ['continent_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_continentweatherinfo_continent_name'), table_name='continentweatherinfo')
    op.drop_column('continentweatherinfo', 'continent_name')
    # ### end Alembic commands ###
