"""create user and chathistory tables

Revision ID: 3586aec30008
Revises: 
Create Date: 2025-10-28 01:35:12.349771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3586aec30008'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userinfo_hashed_password'), 'userinfo', ['hashed_password'], unique=False)
    op.create_index(op.f('ix_userinfo_id'), 'userinfo', ['id'], unique=False)
    op.create_index(op.f('ix_userinfo_user_email'), 'userinfo', ['user_email'], unique=False)
    op.create_table('chathistory',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('chat_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['userinfo.id'], ),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index(op.f('ix_chathistory_chat_id'), 'chathistory', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chathistory_role'), 'chathistory', ['role'], unique=False)
    op.create_index(op.f('ix_chathistory_session_id'), 'chathistory', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chathistory_session_id'), table_name='chathistory')
    op.drop_index(op.f('ix_chathistory_role'), table_name='chathistory')
    op.drop_index(op.f('ix_chathistory_chat_id'), table_name='chathistory')
    op.drop_table('chathistory')
    op.drop_index(op.f('ix_userinfo_user_email'), table_name='userinfo')
    op.drop_index(op.f('ix_userinfo_id'), table_name='userinfo')
    op.drop_index(op.f('ix_userinfo_hashed_password'), table_name='userinfo')
    op.drop_table('userinfo')
    # ### end Alembic commands ###
