"""update email column wiht unique constraint

Revision ID: 878b50c9ad65
Revises: 3586aec30008
Create Date: 2025-10-28 01:52:50.726277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878b50c9ad65'
down_revision: Union[str, Sequence[str], None] = '3586aec30008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userinfo_user_email'), table_name='userinfo')
    op.create_index(op.f('ix_userinfo_user_email'), 'userinfo', ['user_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userinfo_user_email'), table_name='userinfo')
    op.create_index(op.f('ix_userinfo_user_email'), 'userinfo', ['user_email'], unique=False)
    # ### end Alembic commands ###
