"""add: weather metadata table

Revision ID: a929c5493ec7
Revises: 878b50c9ad65
Create Date: 2025-10-30 15:32:23.126945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a929c5493ec7'
down_revision: Union[str, Sequence[str], None] = '878b50c9ad65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('continentweatherinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_continentweatherinfo_id'), 'continentweatherinfo', ['id'], unique=False)
    op.create_index(op.f('ix_continentweatherinfo_weather_metadata'), 'continentweatherinfo', ['weather_metadata'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_continentweatherinfo_weather_metadata'), table_name='continentweatherinfo')
    op.drop_index(op.f('ix_continentweatherinfo_id'), table_name='continentweatherinfo')
    op.drop_table('continentweatherinfo')
    # ### end Alembic commands ###
